--
-- PostgreSQL database dump
--

\restrict mw2rrau5UfoIyvdKERmzGtEvjyCQsPRgH0tkyu6rGLk6KVTF4J1qoEfln2L9b1q

-- Dumped from database version 15.18
-- Dumped by pg_dump version 15.18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.threads DROP CONSTRAINT IF EXISTS fklnm5tg6tlrwc57xdk8iuupoxb;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS fkk8mi2vhyv7chhf0a72g41a8oh;
ALTER TABLE IF EXISTS ONLY public.posts DROP CONSTRAINT IF EXISTS fk40b46jhckoj7eano2hjtbspah;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.board DROP CONSTRAINT IF EXISTS uktptejhppel4ei579p4sce8e1l;
ALTER TABLE IF EXISTS ONLY public.board DROP CONSTRAINT IF EXISTS ukfipjuh5hisfppc2n34giej12x;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS uk2ty1xmrrgtn89xt7kyxx6ta7h;
ALTER TABLE IF EXISTS ONLY public.threads DROP CONSTRAINT IF EXISTS threads_pkey;
ALTER TABLE IF EXISTS ONLY public.posts DROP CONSTRAINT IF EXISTS posts_pkey;
ALTER TABLE IF EXISTS ONLY public.board DROP CONSTRAINT IF EXISTS board_pkey;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.threads;
DROP TABLE IF EXISTS public.posts;
DROP TABLE IF EXISTS public.board;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: board; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.board (
    id bigint NOT NULL,
    createdat bigint NOT NULL,
    life_cycle_posts integer NOT NULL,
    life_cycle_threads integer NOT NULL,
    name character varying(3) NOT NULL,
    rules character varying(12) NOT NULL,
    transcription character varying(255) NOT NULL,
    CONSTRAINT board_check CHECK (((life_cycle_posts < life_cycle_threads) AND (life_cycle_posts >= 1))),
    CONSTRAINT board_life_cycle_threads_check CHECK (((life_cycle_threads >= 2) AND (life_cycle_threads <= 28)))
);


--
-- Name: board_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.board ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.board_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.posts (
    id bigint NOT NULL,
    content character varying(255),
    createdat bigint,
    header character varying(200) NOT NULL,
    picture character varying(255),
    thread bigint
);


--
-- Name: posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: threads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.threads (
    id bigint NOT NULL,
    content character varying(255),
    createdat bigint,
    header character varying(200) NOT NULL,
    picture character varying(255),
    board character varying(3)
);


--
-- Name: threads_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.threads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.threads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    nickname character varying(10) NOT NULL,
    password character varying(255) NOT NULL,
    role boolean NOT NULL,
    board character varying(3)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: board; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.board (id, createdat, life_cycle_posts, life_cycle_threads, name, rules, transcription) FROM stdin;
1	1783673134546	7	14	a	rw-xrw-xrw-x	Main Board
2	1783673684496	7	14	b	rwdxrw-x----	Private Board
\.


--
-- Data for Name: posts; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.posts (id, content, createdat, header, picture, thread) FROM stdin;
1	Hello, Posts!	1783673169586			1
2	1-st private post.	1783673741803			2
3	Пум-пум-пум	1783687974238			7
4	пам пам	1783688049851			7
5	>>3 ссылка на третий пост\r\n	1783688106417			7
6	>>1	1783688316372			7
7	11	1783689375429			8
\.


--
-- Data for Name: threads; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.threads (id, content, createdat, header, picture, board) FROM stdin;
1	Hello, Threads!	1783673157714	Hello, Threads!	[photo_2026-04-21_16-11-37.jpg][1783673157681]	a
2	1-st private thread.	1783673726472	Some head.	[photo_2026-04-21_16-13-04.jpg][1783673726469]	b
3	Summer	1783687263741	Hellow, summer	[Без имени-1.jpg][1783687263737]	a
4	Summer	1783687269644	Hellow, summer	[Без имени-1.jpg][1783687269641]	a
5	Summer	1783687274261	Hellow, summer	[Без имени-1.jpg][1783687274258]	a
6	Summer	1783687289825	Hellow, summer	[Без имени-1.jpg][1783687289821]	a
7	Summer	1783687832114	Summer	[noname.jpg][1783687832110]	a
8	Test	1783688914163	Test	[photo_2026-04-21_16-13-04.jpg][1783688914159]	a
9	Файл с кириллицей в названии	1783690189662	Файл с кириллицей в названии	d9f3c9df-d7ad-4de2-9f56-9b6f9a940829_1783690189648	a
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, nickname, password, role, board) FROM stdin;
1	master	$argon2id$v=19$m=65536,t=3,p=1$tDxcjeDsYc48ra02QUAx8Q$k0zlvyBOIwFBh+TAcNFqOs59dO+2mogtXtc+J+ai11s	t	a
2	Main	$argon2id$v=19$m=65536,t=3,p=1$y5S4mOuu+YkzhkzkQ/vivg$HFmP9tTK7Ekh9KHFqbdB+t0r+otrCT3Svdw9uWyr8VM	t	b
3	tester	$argon2id$v=19$m=65536,t=3,p=1$nPcVgABW8Nf6R5CHlVq1Ow$9rVkTaMd4TIPTzGof4lhnes4A/LAfE8+ZYtcob2a15M	f	b
\.


--
-- Name: board_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.board_id_seq', 2, true);


--
-- Name: posts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.posts_id_seq', 7, true);


--
-- Name: threads_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.threads_id_seq', 9, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 4, true);


--
-- Name: board board_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board
    ADD CONSTRAINT board_pkey PRIMARY KEY (id);


--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);


--
-- Name: threads threads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.threads
    ADD CONSTRAINT threads_pkey PRIMARY KEY (id);


--
-- Name: users uk2ty1xmrrgtn89xt7kyxx6ta7h; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk2ty1xmrrgtn89xt7kyxx6ta7h UNIQUE (nickname);


--
-- Name: board ukfipjuh5hisfppc2n34giej12x; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board
    ADD CONSTRAINT ukfipjuh5hisfppc2n34giej12x UNIQUE (name);


--
-- Name: board uktptejhppel4ei579p4sce8e1l; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board
    ADD CONSTRAINT uktptejhppel4ei579p4sce8e1l UNIQUE (name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: posts fk40b46jhckoj7eano2hjtbspah; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fk40b46jhckoj7eano2hjtbspah FOREIGN KEY (thread) REFERENCES public.threads(id);


--
-- Name: users fkk8mi2vhyv7chhf0a72g41a8oh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkk8mi2vhyv7chhf0a72g41a8oh FOREIGN KEY (board) REFERENCES public.board(name);


--
-- Name: threads fklnm5tg6tlrwc57xdk8iuupoxb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.threads
    ADD CONSTRAINT fklnm5tg6tlrwc57xdk8iuupoxb FOREIGN KEY (board) REFERENCES public.board(name);


--
-- PostgreSQL database dump complete
--

\unrestrict mw2rrau5UfoIyvdKERmzGtEvjyCQsPRgH0tkyu6rGLk6KVTF4J1qoEfln2L9b1q

