--
-- PostgreSQL database dump
--

\restrict vGNzzC9d9jRFGi2jqNGHO2b9Y6UEDRCLVJdLleiZDvJ8Lqelj3bvKdBjltqZ8hD

-- Dumped from database version 15.18
-- Dumped by pg_dump version 15.18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.threads DROP CONSTRAINT IF EXISTS fklnm5tg6tlrwc57xdk8iuupoxb;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS fkk8mi2vhyv7chhf0a72g41a8oh;
ALTER TABLE IF EXISTS ONLY public.posts DROP CONSTRAINT IF EXISTS fk40b46jhckoj7eano2hjtbspah;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.board DROP CONSTRAINT IF EXISTS uktptejhppel4ei579p4sce8e1l;
ALTER TABLE IF EXISTS ONLY public.board DROP CONSTRAINT IF EXISTS ukfipjuh5hisfppc2n34giej12x;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS uk2ty1xmrrgtn89xt7kyxx6ta7h;
ALTER TABLE IF EXISTS ONLY public.threads DROP CONSTRAINT IF EXISTS threads_pkey;
ALTER TABLE IF EXISTS ONLY public.posts DROP CONSTRAINT IF EXISTS posts_pkey;
ALTER TABLE IF EXISTS ONLY public.board DROP CONSTRAINT IF EXISTS board_pkey;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.threads;
DROP TABLE IF EXISTS public.posts;
DROP TABLE IF EXISTS public.board;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: board; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.board (
                              id bigint NOT NULL,
                              createdat bigint NOT NULL,
                              life_cycle_posts integer NOT NULL,
                              life_cycle_threads integer NOT NULL,
                              name character varying(3) NOT NULL,
                              rules character varying(12) NOT NULL,
                              transcription character varying(255) NOT NULL,
                              CONSTRAINT board_check CHECK (((life_cycle_posts < life_cycle_threads) AND (life_cycle_posts >= 1))),
                              CONSTRAINT board_life_cycle_threads_check CHECK (((life_cycle_threads >= 2) AND (life_cycle_threads <= 28)))
);


--
-- Name: board_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.board ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.board_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.posts (
                              id bigint NOT NULL,
                              content character varying(255),
                              createdat bigint,
                              header character varying(200) NOT NULL,
                              picture character varying(255),
                              thread bigint
);


--
-- Name: posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: threads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.threads (
                                id bigint NOT NULL,
                                content character varying(255),
                                createdat bigint,
                                header character varying(200) NOT NULL,
                                picture character varying(255),
                                board character varying(3),
                                carma integer DEFAULT 0 NOT NULL
);


--
-- Name: threads_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.threads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.threads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
                              id bigint NOT NULL,
                              nickname character varying(10) NOT NULL,
                              password character varying(255) NOT NULL,
                              role boolean NOT NULL,
                              board character varying(3)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: board board_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board
    ADD CONSTRAINT board_pkey PRIMARY KEY (id);


--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);


--
-- Name: threads threads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.threads
    ADD CONSTRAINT threads_pkey PRIMARY KEY (id);


--
-- Name: users uk2ty1xmrrgtn89xt7kyxx6ta7h; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk2ty1xmrrgtn89xt7kyxx6ta7h UNIQUE (nickname);


--
-- Name: board ukfipjuh5hisfppc2n34giej12x; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board
    ADD CONSTRAINT ukfipjuh5hisfppc2n34giej12x UNIQUE (name);


--
-- Name: board uktptejhppel4ei579p4sce8e1l; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board
    ADD CONSTRAINT uktptejhppel4ei579p4sce8e1l UNIQUE (name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: posts fk40b46jhckoj7eano2hjtbspah; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fk40b46jhckoj7eano2hjtbspah FOREIGN KEY (thread) REFERENCES public.threads(id);


--
-- Name: users fkk8mi2vhyv7chhf0a72g41a8oh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkk8mi2vhyv7chhf0a72g41a8oh FOREIGN KEY (board) REFERENCES public.board(name);


--
-- Name: threads fklnm5tg6tlrwc57xdk8iuupoxb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.threads
    ADD CONSTRAINT fklnm5tg6tlrwc57xdk8iuupoxb FOREIGN KEY (board) REFERENCES public.board(name);


--
-- PostgreSQL database dump complete
--

\unrestrict vGNzzC9d9jRFGi2jqNGHO2b9Y6UEDRCLVJdLleiZDvJ8Lqelj3bvKdBjltqZ8hD