spring.application.name=jablog
server.port=8080
client.host=https://77.110.115.36.nip.io:3000

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.servlet.multipart.enabled=true
spring.servlet.multipart.resolve-lazily=true

lombok.anyConstructor.addConstructorProperties = true

server.servlet.session.cookie.same-site=Lax